In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset = pd.read_csv('/content/drive/My Drive/dataset/amazonreviews.tsv', sep='\t')
dataset.head(9999)

label                                             review
0      pos  Stuning even for the non-gamer: This sound tra...
1      pos  The best soundtrack ever to anything.: I'm rea...
2      pos  Amazing!: This soundtrack is my favorite music...
3      pos  Excellent Soundtrack: I truly like this soundt...
4      pos  Remember, Pull Your Jaw Off The Floor After He...
...    ...                                                ...
9994   neg  Sorry Jim: As a former realtor, Mr. Cole owes ...
9995   pos  A revelation of life in small town America in ...
9996   pos  Great biography of a very interesting journali...
9997   neg  Interesting Subject; Poor Presentation: You'd ...
9998   neg  Don't buy: The box looked used and it is obvio...

[9999 rows x 2 columns]

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
wl = WordNetLemmatizer()
processed_data = []
for i in range(0, len(dataset)):
    reviews = re.sub('[^a-zA-Z0-9]', ' ', dataset['review'][i])
    reviews = reviews.lower()
    reviews = reviews.split()
    
    reviews = [wl.lemmatize(word) for word in reviews if not word in stopwords.words('english')]
    reviews = ' '.join(reviews)
    processed_data.append(reviews)

In [ ]:
dataset['review'][1]

"The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny."

In [ ]:
processed_data[1]

'best soundtrack ever anything reading lot review saying best game soundtrack figured write review disagree bit opinino yasunori mitsuda ultimate masterpiece music timeless listening year beauty simply refuse fade price tag pretty staggering must say going buy cd much money one feel would worth every penny'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_v=TfidfVectorizer(ngram_range=(1,3)) # ngram fetaures between range 1-3 are added
X_new=tfidf_v.fit_transform(processed_data).toarray()

In [ ]:
X_new.shape

(10000, 5000)

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
dataset['label']= label_encoder.fit_transform(dataset['label'])
Y=dataset['label']

In [ ]:
Y

0       1
1       1
2       1
3       1
4       1
       ..
9995    1
9996    1
9997    0
9998    0
9999    1
Name: label, Length: 10000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.25, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

In [ ]:
model = LogisticRegression(random_state=4)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train)
print("*****Logistic Regression*****")
print("Confusion Matrix: ")
print(cm)
print(class_report)
print('Accuracy Score:', accuracy_score(y_test, y_pred))
print("Mean Accuracy: ", accuracies.mean()*100)
print("Standard Deviation: ", accuracies.std()*100)

*****Logistic Regression*****
Confusion Matrix: 
[[1093  192]
 [ 183 1032]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.85      1285
           1       0.84      0.85      0.85      1215

    accuracy                           0.85      2500
   macro avg       0.85      0.85      0.85      2500
weighted avg       0.85      0.85      0.85      2500

Accuracy Score: 0.85
Mean Accuracy:  84.97333333333333
Standard Deviation:  0.7310266752998803


In [ ]:
x=["this product is okay"]
h=tfidf_v.transform(x)
y=model.predict(h)
def find(y):
    if y == 1:
        print ("Review is positive")
    else:
        print ("Review is negative")

find(y)

Review is negative


In [ ]:
model = RandomForestClassifier(n_estimators=100, criterion = 'entropy')
model.fit(X_train,y_train)
from sklearn import metrics
from sklearn.metrics import classification_report
y_pred = model.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, y_pred)
print("Confusin Matrix: ")
print(cm)
print(classification_report(y_test, y_pred))

accuracy:   0.835
Confusin Matrix: 
[[1076  209]
 [ 204 1011]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84      1285
           1       0.83      0.83      0.83      1215

    accuracy                           0.83      2500
   macro avg       0.83      0.83      0.83      2500
weighted avg       0.83      0.83      0.83      2500



In [ ]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train)
print("*****Naive Bayes*****")
print("Confusion Matrix: ")
print(cm)
print(class_report)
print('Accuracy Score:', accuracy_score(y_test, y_pred))
print("Mean Accuracy: ", accuracies.mean()*100)
print("Standard Deviation: ", accuracies.std()*100)

*****Naive Bayes*****
Confusion Matrix: 
[[957 328]
 [241 974]]
              precision    recall  f1-score   support

           0       0.80      0.74      0.77      1285
           1       0.75      0.80      0.77      1215

    accuracy                           0.77      2500
   macro avg       0.77      0.77      0.77      2500
weighted avg       0.77      0.77      0.77      2500

Accuracy Score: 0.7724
Mean Accuracy:  76.08
Standard Deviation:  1.3665203173673555
